steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/kustomize', '.']
- # Verify kustomize has been built correctly
  name: 'gcr.io/$PROJECT_ID/kustomize'
  entrypoint: 'kustomize'
  args: ['version']
- # Verify make exists been built correctly
  name: 'gcr.io/$PROJECT_ID/kustomize'
  entrypoint: 'make'
  args: ['-h']

images: ['gcr.io/$PROJECT_ID/kustomize']
tags: ['cloud-builders-community']
